version: '3.2'
networks:
    default:
      external:
        name: frigate-network

services:
    frigate-zookeeper:
        build: ./zookeeper
        entrypoint: /opt/kafka_2.12-2.4.0/bin/zookeeper-server-start.sh zookeeper.properties
        image: 127.0.0.1:5001/zookeeper
        
    frigate-kafka:
        build: ./kafka        
        entrypoint: ./wait-for-it.sh frigate-zookeeper:2181 --strict -- /opt/kafka_2.12-2.4.0/bin/kafka-server-start.sh server.properties
        image: 127.0.0.1:5001/kafka        
        depends_on:
            - frigate-zookeeper

    frigate-kafka-setup:
        build: ./kafka-setup
        environment: 
            - TOPIC_PARTITIONS=2
            - KAFKA_HOME=/opt/kafka_2.12-2.4.0
        entrypoint: ./wait-for-it.sh frigate-kafka:9092 --strict -- ./kafka-setup.sh
        image: 127.0.0.1:5001/kafka-setup
        depends_on:
            - frigate-kafka

    
    frigate-stream-0:
        build: ./stream        
        entrypoint: ./wait-for-it.sh frigate-kafka-setup:8080 --strict -- faust --debug -A stream_worker worker -l info --web-bind 0.0.0.0 --web-port 6066
        image: 127.0.0.1:5001/stream                
        environment: 
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/0/33/roadnet.net.xml
            - TOPIC_PARTITIONS=2
            - KAFKA_BROKER_URL_2=kafka://frigate-kafka
            - ETA=0.5
        ports:
            - mode: ingress
              protocol: tcp
              published: 6066
              target: 6066
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
    
    frigate-stream-1:
        build: ./stream        
        entrypoint: ./wait-for-it.sh frigate-kafka-setup:8080 --strict -- faust --debug -A stream_worker worker -l info --web-bind 0.0.0.0 --web-port 6067
        image: 127.0.0.1:5001/stream                
        environment: 
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/0/33/roadnet.net.xml
            - TOPIC_PARTITIONS=2
            - KAFKA_BROKER_URL_2=kafka://frigate-kafka
            - ETA=0.5
        ports:
            - mode: ingress
              protocol: tcp
              published: 6067
              target: 6067
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
    

    frigate-endpoint:
        build: ./endpoint
        entrypoint: ./wait-for-it.sh frigate-stream-0:6066 --strict -- ./wait-for-it.sh frigate-stream-1:6067 --strict -- python endpoint_server.py
        image: 127.0.0.1:5001/endpoint
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/0/33/roadnet.net.xml
            - ENDPOINT_SERVER_HOST=0.0.0.0
            - ENDPOINT_SERVER_PORT=8009
            - KAFKA_BROKER_URL=frigate-kafka:9092
            - STREAM_SERVICE_WEB_URL=frigate-stream-0:6066
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            
            - frigate-stream-0
            
            - frigate-stream-1
            
    
    
    frigate-simulator-0:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/0/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/0/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8010
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8010
              target: 8010
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        
    frigate-simulator-1:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/1/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/1/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8011
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8011
              target: 8011
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        
    frigate-simulator-2:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/2/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/2/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8012
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8012
              target: 8012
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        
    frigate-simulator-3:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/3/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/3/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8013
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8013
              target: 8013
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        
    frigate-simulator-4:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/4/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/4/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8014
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8014
              target: 8014
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        
    frigate-simulator-5:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/5/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/5/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8015
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8015
              target: 8015
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        
    frigate-simulator-6:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/6/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/6/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8016
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8016
              target: 8016
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        
    frigate-simulator-7:
        build: ./simulator
        entrypoint: ./wait-for-it.sh frigate-endpoint:8009 --strict -- python simulator_server.py
        image: 127.0.0.1:5001/simulator
        environment: 
            - SUMO_HOME=/opt/sumo-1_1_0
            - SUMO_TOOLS_HOME=/opt/sumo-1_1_0/tools
            - SUMO_ROADNET_PATH=/var/data/dag_test_output/7/33/roadnet.net.xml
            - SUMO_STEPS=1000
            - SUMO_BINARY=/opt/sumo-1_1_0/bin/sumo
            - SUMO_SIM_FILE=/var/data/dag_test_output/7/33/simulation.sumocfg
            - VEHICLES_TO_ROUTE=PERIODICAL_STEP
            - ROUTING_STEP_PERIOD=10
            - ENDPOINT_SERVER_PORT=8009
            - ENDPOINT_SERVER_HOST=frigate-endpoint
            - SIMULATOR_SERVER_PORT=8017
            - SIMULATOR_SERVER_HOST=0.0.0.0
        ports:
            - mode: ingress
              protocol: tcp
              published: 8017
              target: 8017
        volumes:
            - type: bind
              source: ./data
              target: /var/data
        depends_on:
            - frigate-zookeeper
            - frigate-kafka
            - frigate-kafka-setup
            - frigate-endpoint
            
            - frigate-stream-0
            
            - frigate-stream-1
            
        